### ISSUE TITLE
bug(extension): GNOME 3.32 support

### ISSUE THREAD

**Issue by protopopov1122** [TimurKiyivinski/gnome-shell-night-light-slider-extension#44]
**Describe the bug**
Extension does not work with GNOME Shell 3.32. In the log appears following line:
```
Mar 16 11:19:36 ArchNotebook gnome-shell[19525]: Extension "night-light-slider.timur@linux.com" had error: TypeError: this._construct is not a function
```
Most probably the issue is connected with recent GNOME Shell changes which break `Lang.Class` in favor of ES6 classes.
https://gitlab.gnome.org/GNOME/gnome-shell/commit/bacfdbbb0338b94295c64093523bca7ba8d5c5ca

**System Information:**
- OS: Arch Linux (last updated on Mar 16)
- GNOME Version: 3.32.0
